apiVersion: v1
kind: ReplicationController
metadata:
  name: javawebapprc
  namespace: test-ns
spec:
  replicas: 1
  selector:
    app: javawebapp
  template:
    metadata: 
      name: javawebapppod
      namespace: test-ns
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebappcontainer
        image: docker8955/java-web-application:$BUILD_NUMBER
        ports:
        - containerPort: 8080

