apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp-deployment
  namespace: test-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata: 
      namespace: test-ns
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebappcontainer
        image: docker8955/java-web-application:$BUILD_NUMBER
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
  namespace: test-ns
spec:
  type: NodePort
  selector: 
    app: javawebapp
  ports: 
  - port: 80
    targetPort: 8080
